<a href="https://colab.research.google.com/github/surajprakash-data-science/MMM-Using-Google-Meridian/blob/main/MMM_using_Meridian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --upgrade google-meridian[colab,and-cuda,schema]

Collecting google-meridian[and-cuda,colab,schema]
  Downloading google_meridian-1.7.0-py3-none-any.whl.metadata (10 kB)
Collecting arviz<0.20.0 (from google-meridian[and-cuda,colab,schema])
  Downloading arviz-0.19.0-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: altair>=5 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (5.5.0)
Collecting bidict (from google-meridian[and-cuda,colab,schema])
  Downloading bidict-0.23.1-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: immutabledict in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (4.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (1.5.3)
Requirement already satisfied: matplotlib<3.11.0 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (3.10.0)
Collecting natsort<8,>=7.1.1 (from google-meridian[and-cuda,colab,schema])
  Downloading natsort-7.1.1-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: numpy<2.4.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (2.0.2)
Requirement already satisfied: pandas<3,>=2.2.2 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (2.2.2)
Requirement already satisfied: scipy<2,>=1.13.1 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (1.16.3)
Requirement already satisfied: statsmodels>=0.14.5 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (0.14.6)
Requirement already satisfied: tensorflow<2.21,>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (2.20.0)
Collecting tfp-nightly==0.26.0.dev20260130 (from google-meridian[and-cuda,colab,schema])
  Downloading tfp_nightly-0.26.0.dev20260130-py2.py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: tf-keras<2.21,>=2.18 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (2.20.0)
Requirement already satisfied: xarray in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (2025.12.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,colab,schema]) (5.9.5)
Collecting python-calamine (from google-meridian[and-cuda,colab,schema])
  Downloading python_calamine-0.7.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.1 kB)
Collecting mmm-proto-schema>=1.2.1 (from google-meridian[and-cuda,colab,schema])
  Downloading mmm_proto_schema-1.2.2-py3-none-any.whl.metadata (1.7 kB)
Collecting semver (from google-meridian[and-cuda,colab,schema])
  Downloading semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,colab,schema]) (1.4.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,colab,schema]) (1.17.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,colab,schema]) (4.4.2)
Requirement already satisfied: cloudpickle>=1.3 in /usr/local/lib/python3.12/dist-packages (from tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,colab,schema]) (3.1.2)
Requirement already satisfied: gast>=0.3.2 in /usr/local/lib/python3.12/dist-packages (from tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,colab,schema]) (0.7.0)
Requirement already satisfied: dm-tree in /usr/local/lib/python3.12/dist-packages (from tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,colab,schema]) (0.1.10)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair>=5->google-meridian[and-cuda,colab,schema]) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair>=5->google-meridian[and-cuda,colab,schema]) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair>=5->google-meridian[and-cuda,colab,schema]) (2.22.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from altair>=5->google-meridian[and-cuda,colab,schema]) (26.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from altair>=5->google-meridian[and-cuda,colab,schema]) (4.15.0)
Requirement already satisfied: setuptools>=60.0.0 in /usr/local/lib/python3.12/dist-packages (from arviz<0.20.0->google-meridian[and-cuda,colab,schema]) (75.2.0)
Requirement already satisfied: h5netcdf>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from arviz<0.20.0->google-meridian[and-cuda,colab,schema]) (1.8.1)
Requirement already satisfied: xarray-einstats>=0.3 in /usr/local/lib/python3.12/dist-packages (from arviz<0.20.0->google-meridian[and-cuda,colab,schema]) (0.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11.0->google-meridian[and-cuda,colab,schema]) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11.0->google-meridian[and-cuda,colab,schema]) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11.0->google-meridian[and-cuda,colab,schema]) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11.0->google-meridian[and-cuda,colab,schema]) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11.0->google-meridian[and-cuda,colab,schema]) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11.0->google-meridian[and-cuda,colab,schema]) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11.0->google-meridian[and-cuda,colab,schema]) (2.9.0.post0)
Requirement already satisfied: googleapis-common-protos in /usr/local/lib/python3.12/dist-packages (from mmm-proto-schema>=1.2.1->google-meridian[and-cuda,colab,schema]) (1.75.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from mmm-proto-schema>=1.2.1->google-meridian[and-cuda,colab,schema]) (5.29.6)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=2.2.2->google-meridian[and-cuda,colab,schema]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=2.2.2->google-meridian[and-cuda,colab,schema]) (2026.2)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.14.5->google-meridian[and-cuda,colab,schema]) (1.0.2)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (25.12.19)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (3.4.0)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (2.32.4)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (3.3.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (2.2.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (1.81.1)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (3.13.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (0.5.4)
Requirement already satisfied: nvidia-cublas-cu12<13.0,>=12.5.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema]) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-cupti-cu12<13.0,>=12.5.82 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema]) (12.8.90)
Requirement already satisfied: nvidia-cuda-nvcc-cu12<13.0,>=12.5.82 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema]) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12<13.0,>=12.5.82 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema]) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12<13.0,>=12.5.82 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema]) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12<10.0,>=9.3.0.75 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema]) (9.19.0.56)
Requirement already satisfied: nvidia-cufft-cu12<12.0,>=11.2.3.61 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema]) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12<11.0,>=10.3.6.82 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema]) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12<12.0,>=11.6.3.83 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema]) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12<13.0,>=12.5.1.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema]) (12.5.8.93)
Requirement already satisfied: nvidia-nccl-cu12<3.0,>=2.25.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema]) (2.28.9)
Requirement already satisfied: nvidia-nvjitlink-cu12<13.0,>=12.5.82 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,colab,schema]) (12.8.93)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (0.47.0)
Requirement already satisfied: attrs>=18.2.0 in /usr/local/lib/python3.12/dist-packages (from dm-tree->tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,colab,schema]) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair>=5->google-meridian[and-cuda,colab,schema]) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair>=5->google-meridian[and-cuda,colab,schema]) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair>=5->google-meridian[and-cuda,colab,schema]) (2026.5.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (0.19.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (2026.6.17)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (3.1.8)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair>=5->google-meridian[and-cuda,colab,schema]) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,colab,schema]) (0.1.2)
Downloading tfp_nightly-0.26.0.dev20260130-py2.py3-none-any.whl (7.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 74.5 MB/s eta 0:00:00
Downloading arviz-0.19.0-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 53.9 MB/s eta 0:00:00
Downloading mmm_proto_schema-1.2.2-py3-none-any.whl (72 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 9.0 MB/s eta 0:00:00
Downloading natsort-7.1.1-py3-none-any.whl (35 kB)
Downloading bidict-0.23.1-py3-none-any.whl (32 kB)
Downloading google_meridian-1.7.0-py3-none-any.whl (503 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 503.6/503.6 kB 29.6 MB/s eta 0:00:00
Downloading python_calamine-0.7.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (952 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 952.4/952.4 kB 61.2 MB/s eta 0:00:00
Downloading semver-3.0.4-py3-none-any.whl (17 kB)
Installing collected packages: semver, python-calamine, natsort, bidict, tfp-nightly, mmm-proto-schema, arviz, google-meridian
  Attempting uninstall: natsort
    Found existing installation: natsort 8.4.0
    Uninstalling natsort-8.4.0:
      Successfully uninstalled natsort-8.4.0
  Attempting uninstall: arviz
    Found existing installation: arviz 0.22.0
    Uninstalling arviz-0.22.0:
      Successfully uninstalled arviz-0.22.0
Successfully installed arviz-0.19.0 bidict-0.23.1 google-meridian-1.7.0 mmm-proto-schema-1.2.2 natsort-7.1.1 python-calamine-0.7.0 semver-3.0.4 tfp-nightly-0.26.0.dev20260130

In [ ]:
import IPython
from meridian import constants
from meridian.analysis import analyzer
from meridian.analysis import optimizer
from meridian.analysis import summarizer
from meridian.analysis import visualizer
from meridian.analysis.review import reviewer
from meridian.data import data_frame_input_data_builder
from meridian.model import model
from meridian.model import prior_distribution
from meridian.model import spec
from meridian.model.eda import meridian_eda
from meridian.schema.serde import meridian_serde
import numpy as np
import pandas as pd
# check if GPU is available
from psutil import virtual_memory
import tensorflow as tf
import tensorflow_probability as tfp

ram_gb = virtual_memory().total / 1e9
print('Your runtime has {:.1f} gigabytes of available RAM\n'.format(ram_gb))
print(
    'Num GPUs Available: ',
    len(tf.config.experimental.list_physical_devices('GPU')),
)
print(
    'Num CPUs Available: ',
    len(tf.config.experimental.list_physical_devices('CPU')),
)

Your runtime has 13.6 gigabytes of available RAM

Num GPUs Available:  1
Num CPUs Available:  1

In [ ]:
import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Create a date range for 2 years (weekly)
dates = pd.date_range(start='2024-01-01', periods=104, freq='W')

# Generate Media Spend (with some randomness)
google_search_spend = np.random.normal(1500, 300, 104).clip(500)
meta_social_spend = np.random.normal(2000, 500, 104).clip(500)
tiktok_video_spend = np.random.normal(1000, 400, 104).clip(200)

# Generate Impressions (proportional to spend with some noise)
google_search_impressions = (google_search_spend * np.random.uniform(5, 8, 104) + np.random.normal(0, 5000, 104)).astype(int).clip(10000)
meta_social_impressions = (meta_social_spend * np.random.uniform(7, 10, 104) + np.random.normal(0, 7000, 104)).astype(int).clip(15000)
tiktok_video_impressions = (tiktok_video_spend * np.random.uniform(6, 9, 104) + np.random.normal(0, 4000, 104)).astype(int).clip(8000)

# Generate Control Variables
promo_active = np.random.choice([0, 1], size=104, p=[0.8, 0.2])
avg_price = np.where(promo_active == 1, 35, 50)
organic_traffic = np.random.normal(3000, 500, 104)

# Create the Revenue (Target) based on a formula + noise
# Formula: Base + (Google * 1.5) + (Meta_Lagged * 1.2) + (TikTok * 0.8) + (Promo_Effect)
base_revenue = 5000
revenue = (
    base_revenue +
    (google_search_spend * 2.2) +
    (pd.Series(meta_social_spend).shift(1).fillna(1000) * 1.8) + # Meta has a 1-week lag
    (tiktok_video_spend * 1.1) +
    (promo_active * 5000) +
    (np.random.normal(0, 1000, 104)) # Adding noise
)

# Create DataFrame
df = pd.DataFrame({
    'time': dates,
    'revenue': revenue.astype(int),
    'google_search_spend': google_search_spend.astype(int),
    'google_search_impressions': google_search_impressions,
    'meta_social_spend': meta_social_spend.astype(int),
    'meta_social_impressions': meta_social_impressions,
    'tiktok_video_spend': tiktok_video_spend.astype(int),
    'tiktok_video_impressions': tiktok_video_impressions,
    'organic_traffic': organic_traffic.astype(int),
    'promo_active': promo_active,
    'avg_price': avg_price
})

# Save to CSV
df.to_csv('marketing_mix_data.csv', index=False)
print("Dummy data for MMM project generated successfully!")

Dummy data for MMM project generated successfully!

In [ ]:
df.head()

,time,revenue,google_search_spend,google_search_impressions,meta_social_spend,meta_social_impressions,tiktok_video_spend,tiktok_video_impressions,organic_traffic,promo_active,avg_price
0,2024-01-07,12298,1649,16711,1919,16305,1206,12127,2958,0,50
1,2024-01-14,14088,1458,10000,2202,16055,2541,20952,3558,0,50
2,2024-01-21,14814,1694,10000,2943,30212,1228,10223,3171,0,50
3,2024-01-28,13353,1956,17542,2087,35173,1454,8000,3228,0,50
4,2024-02-04,19571,1429,10000,2128,18931,1381,8374,3284,1,35

In [ ]:
df.dtypes

time                         datetime64[ns]
revenue                               int64
google_search_spend                   int64
google_search_impressions             int64
meta_social_spend                     int64
meta_social_impressions               int64
tiktok_video_spend                    int64
tiktok_video_impressions              int64
organic_traffic                       int64
promo_active                          int64
avg_price                             int64
dtype: object

## Data Notes

This synthetic dataset represents weekly marketing and sales data for a hypothetical product over two years (104 weeks). It includes:

*   **`date`**: Weekly date.
*   **`revenue`**: The target variable, representing weekly revenue.
*   **`google_search_spend`**, **`meta_social_spend`**, **`tiktok_video_spend`**: Weekly advertising spend on different platforms.
*   **`google_search_impressions`**, **`meta_social_impressions`**, **`tiktok_video_impressions`**: Weekly impressions generated by advertising on different platforms.
*   **`organic_traffic`**: Baseline organic website traffic, acting as a control variable.
*   **`promo_active`**: A binary flag (0 or 1) indicating if a promotion was active during that week.
*   **`avg_price`**: The average price of the product, which varies based on promotion activity.

The `revenue` is generated based on a formula that incorporates media spend (with a 1-week lag for Meta social spend), promotional effects, and random noise to simulate real-world variability.

## Define Column Categories

To prepare the data for Marketing Mix Modeling, we'll categorize the DataFrame columns into several groups:

*   **KPI (Key Performance Indicator)**: The primary metric we want to model (`revenue`).
*   **Media**: Variables related to advertising spend and impressions across different platforms.
*   **Non-Media**: Control variables that are not directly media-related but can influence the KPI (e.g., `promo_active`, `avg_price`).
*   **Organic**: Variables representing organic growth or baseline activity (e.g., `organic_traffic`).

# **Defining Data**

In [ ]:
# Define the column categories
kpi_col = ['revenue']

media_spend_cols = [
    'google_search_spend',
    'meta_social_spend',
    'tiktok_video_spend'
]

media_impressions_cols = [
    'google_search_impressions',
    'meta_social_impressions',
    'tiktok_video_impressions'
]

non_media_control_cols = [
    'promo_active'
]

organic_cols = [
    'organic_traffic'
]

print("Column categories defined successfully.")

Column categories defined successfully.

In [ ]:
builder = data_frame_input_data_builder.DataFrameInputDataBuilder(
    kpi_type='revenue',
    default_time_column='time',
    default_kpi_column='revenue'
    #,default_geo_column='geo'
)

builder.with_kpi(df, kpi_col='revenue')
builder.with_controls(df, control_cols=non_media_control_cols)
builder.with_media(
    df=df,
    media_cols=[
        'google_search_impressions',
        'meta_social_impressions',
        'tiktok_video_impressions'
    ],
    media_spend_cols=[
        'google_search_spend',
        'meta_social_spend',
        'tiktok_video_spend'
    ],
    media_channels=[
        'Google Search',
        'Meta Social',
        'TikTok Video'
    ]
)

# 4. Add organic channels using parallel lists
builder.with_organic_media(
    df=df,
    organic_media_cols=['organic_traffic'],
    organic_media_channels=['Organic Traffic']
)

input_data = builder.build()

/usr/local/lib/python3.12/dist-packages/meridian/data/input_data.py:517: UserWarning: Revenue from the `kpi` data is used when `kpi_type`=`revenue`. `revenue_per_kpi` is ignored.
  warnings.warn(

## Data Definition Notes

The `InputData` object has been successfully created using the `DataFrameInputDataBuilder`. This object encapsulates the marketing mix data, including:

*   **KPI**: `revenue`
*   **Time Column**: `time`
*   **Media Spend Columns**: `google_search_spend`, `meta_social_spend`, `tiktok_video_spend`
*   **Media Impressions Columns**: `google_search_impressions`, `meta_social_impressions`, `tiktok_video_impressions`
*   **Control Columns**: `promo_active`, `avg_price`
*   **Organic Columns**: `organic_traffic`

This `InputData` object is now ready for further analysis and model building within the Meridian framework.

# **Model configuration**

In [ ]:
roi_mu = 0.2  # Mu for ROI prior for each media channel.
roi_sigma = 0.9  # Sigma for ROI prior for each media channel.

prior = prior_distribution.PriorDistribution(
    roi_m=tfp.distributions.LogNormal(roi_mu, roi_sigma, name=constants.ROI_M)
)
model_spec = spec.ModelSpec(prior=prior, enable_aks=True)

mmm = model.Meridian(input_data=input_data, model_spec=model_spec)

/usr/local/lib/python3.12/dist-packages/meridian/model/model.py:103: UserWarning: In a nationally aggregated model, the `media_effects_dist` will be reset to `normal`.
  warnings.warn(

In [ ]:
mmm.sample_prior(500)

/usr/local/lib/python3.12/dist-packages/meridian/model/prior_distribution.py:1329: UserWarning: Hierarchical distribution parameters must be deterministically zero for national models. tau_g_excl_baseline has been automatically set to Deterministic(0).
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/model/prior_distribution.py:1329: UserWarning: Hierarchical distribution parameters must be deterministically zero for national models. eta_m has been automatically set to Deterministic(0).
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/model/prior_distribution.py:1329: UserWarning: Hierarchical distribution parameters must be deterministically zero for national models. eta_rf has been automatically set to Deterministic(0).
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/model/prior_distribution.py:1329: UserWarning: Hierarchical distribution parameters must be deterministically zero for national models. eta_om has been automatically set to Deterministic(0).
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/model/prior_distribution.py:1329: UserWarning: Hierarchical distribution parameters must be deterministically zero for national models. eta_orf has been automatically set to Deterministic(0).
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/model/prior_distribution.py:1329: UserWarning: Hierarchical distribution parameters must be deterministically zero for national models. xi_c has been automatically set to Deterministic(0).
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/model/prior_distribution.py:1329: UserWarning: Hierarchical distribution parameters must be deterministically zero for national models. xi_n has been automatically set to Deterministic(0).
  warnings.warn(

## Model Configuration Notes

-   **ROI Prior**: A prior distribution for Return on Investment (ROI) has been set for each media channel. Specifically, a `LogNormal` distribution with `roi_mu = 0.2` and `roi_sigma = 0.9` is used.
-   **Model Specification**: A `ModelSpec` object was created, incorporating the defined ROI prior and enabling Automatic Kalman Smoothing (`enable_aks=True`).
-   **Meridian Model Initialization**: The `Meridian` model was initialized using the `input_data` object (created in the data definition step) and the `model_spec` object. This sets up the framework for the Marketing Mix Model.

# **EDA**

In [ ]:
eda = meridian_eda.MeridianEDA(mmm)
filename = 'eda_report.pdf'
meridian_root = '/content/'
eda.generate_and_save_report(filename=filename, filepath=meridian_root)
IPython.display.HTML(filename=f'{meridian_root}/{filename}')

1. The Critical Issue: Relationship Among Variables (The "FAIL")
This is the most important part of the report. The model has flagged a Multicollinearity error.
The Problem: The variables promo_active and avg_price have a pairwise correlation of -0.999 (nearly perfect negative correlation).
The VIF (Variance Inflation Factor): Both variables show a VIF of "inf" (Infinite).
What this means: In your data, every time a promotion is active, the price drops by a fixed, predictable amount. Because they move perfectly together, the model cannot distinguish which one is actually driving sales.
Recommended Action: You cannot include both variables in the model. You must either:
Drop one of them.
Combine them into a single "Price with Promo" index.
If you keep both, the model will likely fail to converge or give you nonsensical results.
2. Individual Explanatory Variables (Warnings)
This section looks at the "signal" in your data.
Low Variability (The "Zero Std Dev" Warning): After removing outliers, promo_active and avg_price show 0.000 variability.
This suggests that for the vast majority of your 104 weeks, these values never changed. If a variable doesn't change, the model can't learn how it affects the KPI.
Outliers: The report flagged several "Extreme" weeks:
Google Search had a massive spike on Sept 28, 2025.
TikTok Video had a spike on Jan 14, 2024.
Action: You should check these dates. Was there a data entry error? Or was there a viral moment or a massive tracking glitch? If these spikes are "fake," they will skew your ROI results.
3. Spend and Media Units
This section evaluates how your budget is distributed and if you have enough data to support the model's complexity.
Spend Share:
Meta Social: 44.9%
Google Search: 32.3%
TikTok Video: 22.8%
Insight: Your spend is relatively well-distributed. None of the channels are so small (e.g., <1%) that they would be impossible to measure.
Data Adequacy:
Your Ratio is 9.45. Meridian generally looks for a ratio where data points significantly outnumber the parameters being estimated.
With 104 weeks (2 years) of data and only 1 geo (national), you are in a "safe" zone, but you don't have a massive amount of "extra" data.
Cost Per Unit Outlier:
On Feb 16, 2025, the TikTok Cost Per Media Unit spiked to 0.206.
Action: Verify if TikTok actually became twice as expensive that week, or if the "Media Units" (Impressions/Clicks) were under-reported.
4. Summary of Data Stats
n_geos: 1 (This is a National-level model).
n_times: 104 (You have exactly 2 years of weekly data).
n_parameters: 11 (The model is trying to calculate 11 different "moving parts").
Knot count: 5 (This is used to control for seasonality/trends).

# **Fit Model**

In [ ]:
mmm.sample_posterior(
    n_chains=5, n_adapt=1000, n_burnin=500, n_keep=1000, seed=0
)

/usr/local/lib/python3.12/dist-packages/arviz/data/inference_data.py:157: UserWarning: trace group is not defined in the InferenceData scheme
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/arviz/data/inference_data.py:1647: UserWarning: trace group is not defined in the InferenceData scheme
  warnings.warn(

In [ ]:
health_summary = reviewer.ModelReviewer(mmm).run()

filename = 'health_card.html'
health_summary.output_model_health_card(filename=filename, filepath=meridian_root)
IPython.display.HTML(filename=f'{meridian_root}{filename}')

/tmp/ipykernel_440/879150696.py:1: DeprecationWarning: The `meridian` argument is deprecated. Please use `model_context` and `inference_data` instead.
  health_summary = reviewer.ModelReviewer(mmm).run()
/usr/local/lib/python3.12/dist-packages/meridian/analysis/analyzer.py:102: UserWarning: The `aggregate_geos` argument is ignored in the national model. It will be reset to `True`.
  warnings.warn(

# **Run model diagnostics**

In [ ]:
model_diagnostics = visualizer.ModelDiagnostics(mmm)
model_diagnostics.plot_rhat_boxplot()

alt.LayerChart(...)

In [ ]:
model_fit = visualizer.ModelFit(mmm)
model_fit.plot_model_fit()

/usr/local/lib/python3.12/dist-packages/meridian/analysis/analyzer.py:102: UserWarning: The `aggregate_geos` argument is ignored in the national model. It will be reset to `True`.
  warnings.warn(

alt.LayerChart(...)

# **model results & two-page output**

In [ ]:
mmm_summarizer = summarizer.Summarizer(mmm)

In [ ]:
filepath = meridian_root
start_date = df['time'].min().strftime('%Y-%m-%d') # Use the earliest date from the dataframe
end_date = df['time'].max().strftime('%Y-%m-%d') # Use the latest date from the dataframe
mmm_summarizer.output_model_results_summary(
    'summary_output.html', filepath, start_date, end_date
)

/usr/local/lib/python3.12/dist-packages/meridian/analysis/analyzer.py:102: UserWarning: The `aggregate_geos` argument is ignored in the national model. It will be reset to `True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/analysis/analyzer.py:102: UserWarning: The `aggregate_geos` argument is ignored in the national model. It will be reset to `True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/analysis/analyzer.py:2700: UserWarning: Effectiveness is not reported because it does not have a clear interpretation by time period.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/analysis/analyzer.py:352: UserWarning: Setting `use_kpi=True` has no effect when `kpi_type=REVENUE` since in this case, KPI is equal to revenue.
  warnings.warn(

In [ ]:
IPython.display.HTML(filename=f'{meridian_root}/summary_output.html')

# **Report**

In [ ]:
%%time
budget_optimizer = optimizer.BudgetOptimizer(mmm)
optimization_results = budget_optimizer.optimize()

CPU times: user 1min 7s, sys: 3.11 s, total: 1min 11s
Wall time: 1min 7s

In [ ]:
filepath = meridian_root
optimization_results.output_optimization_summary(
    'optimization_output.html', filepath
)

In [ ]:
IPython.display.HTML(filename=f'{meridian_root}/optimization_output.html')

In [ ]:
# Grant Colab access to create Google Sheet in your Drive
from google.colab import auth

_SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive",
]
credentials = auth.authenticate_user(_SCOPES)

In [ ]:
!pip install google-meridian[scenarioplanner,and-cuda]

Requirement already satisfied: google-meridian[and-cuda,scenarioplanner] in /usr/local/lib/python3.12/dist-packages (1.7.0)
Requirement already satisfied: arviz<0.20.0 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (0.19.0)
Requirement already satisfied: altair>=5 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (5.5.0)
Requirement already satisfied: bidict in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (0.23.1)
Requirement already satisfied: immutabledict in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (4.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (1.5.3)
Requirement already satisfied: matplotlib<3.11.0 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (3.10.0)
Requirement already satisfied: natsort<8,>=7.1.1 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (7.1.1)
Requirement already satisfied: numpy<2.4.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (2.0.2)
Requirement already satisfied: pandas<3,>=2.2.2 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (2.2.2)
Requirement already satisfied: scipy<2,>=1.13.1 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (1.16.3)
Requirement already satisfied: statsmodels>=0.14.5 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (0.14.6)
Requirement already satisfied: tensorflow<2.21,>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (2.20.0)
Requirement already satisfied: tfp-nightly==0.26.0.dev20260130 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (0.26.0.dev20260130)
Requirement already satisfied: tf-keras<2.21,>=2.18 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (2.20.0)
Requirement already satisfied: xarray in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (2025.12.0)
Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (2.197.0)
Requirement already satisfied: google-auth in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (2.49.0)
Requirement already satisfied: mmm-proto-schema>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (1.2.2)
Requirement already satisfied: semver in /usr/local/lib/python3.12/dist-packages (from google-meridian[and-cuda,scenarioplanner]) (3.0.4)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,scenarioplanner]) (1.4.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,scenarioplanner]) (1.17.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,scenarioplanner]) (4.4.2)
Requirement already satisfied: cloudpickle>=1.3 in /usr/local/lib/python3.12/dist-packages (from tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,scenarioplanner]) (3.1.2)
Requirement already satisfied: gast>=0.3.2 in /usr/local/lib/python3.12/dist-packages (from tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,scenarioplanner]) (0.7.0)
Requirement already satisfied: dm-tree in /usr/local/lib/python3.12/dist-packages (from tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,scenarioplanner]) (0.1.10)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair>=5->google-meridian[and-cuda,scenarioplanner]) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair>=5->google-meridian[and-cuda,scenarioplanner]) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair>=5->google-meridian[and-cuda,scenarioplanner]) (2.22.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from altair>=5->google-meridian[and-cuda,scenarioplanner]) (26.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from altair>=5->google-meridian[and-cuda,scenarioplanner]) (4.15.0)
Requirement already satisfied: setuptools>=60.0.0 in /usr/local/lib/python3.12/dist-packages (from arviz<0.20.0->google-meridian[and-cuda,scenarioplanner]) (75.2.0)
Requirement already satisfied: h5netcdf>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from arviz<0.20.0->google-meridian[and-cuda,scenarioplanner]) (1.8.1)
Requirement already satisfied: xarray-einstats>=0.3 in /usr/local/lib/python3.12/dist-packages (from arviz<0.20.0->google-meridian[and-cuda,scenarioplanner]) (0.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11.0->google-meridian[and-cuda,scenarioplanner]) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11.0->google-meridian[and-cuda,scenarioplanner]) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11.0->google-meridian[and-cuda,scenarioplanner]) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11.0->google-meridian[and-cuda,scenarioplanner]) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11.0->google-meridian[and-cuda,scenarioplanner]) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11.0->google-meridian[and-cuda,scenarioplanner]) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11.0->google-meridian[and-cuda,scenarioplanner]) (2.9.0.post0)
Requirement already satisfied: googleapis-common-protos in /usr/local/lib/python3.12/dist-packages (from mmm-proto-schema>=1.2.1->google-meridian[and-cuda,scenarioplanner]) (1.75.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from mmm-proto-schema>=1.2.1->google-meridian[and-cuda,scenarioplanner]) (5.29.6)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=2.2.2->google-meridian[and-cuda,scenarioplanner]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=2.2.2->google-meridian[and-cuda,scenarioplanner]) (2026.2)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.14.5->google-meridian[and-cuda,scenarioplanner]) (1.0.2)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (25.12.19)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (3.4.0)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (2.32.4)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (3.3.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (2.2.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (1.81.1)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (3.13.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (0.5.4)
Requirement already satisfied: nvidia-cublas-cu12<13.0,>=12.5.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,scenarioplanner]) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-cupti-cu12<13.0,>=12.5.82 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,scenarioplanner]) (12.8.90)
Requirement already satisfied: nvidia-cuda-nvcc-cu12<13.0,>=12.5.82 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,scenarioplanner]) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12<13.0,>=12.5.82 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,scenarioplanner]) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12<13.0,>=12.5.82 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,scenarioplanner]) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12<10.0,>=9.3.0.75 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,scenarioplanner]) (9.19.0.56)
Requirement already satisfied: nvidia-cufft-cu12<12.0,>=11.2.3.61 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,scenarioplanner]) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12<11.0,>=10.3.6.82 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,scenarioplanner]) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12<12.0,>=11.6.3.83 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,scenarioplanner]) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12<13.0,>=12.5.1.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,scenarioplanner]) (12.5.8.93)
Requirement already satisfied: nvidia-nccl-cu12<3.0,>=2.25.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,scenarioplanner]) (2.28.9)
Requirement already satisfied: nvidia-nvjitlink-cu12<13.0,>=12.5.82 in /usr/local/lib/python3.12/dist-packages (from tensorflow[and-cuda]<2.21,>=2.19.0; extra == "and-cuda"->google-meridian[and-cuda,scenarioplanner]) (12.8.93)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-meridian[and-cuda,scenarioplanner]) (0.31.2)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-meridian[and-cuda,scenarioplanner]) (0.4.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-meridian[and-cuda,scenarioplanner]) (2.30.3)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-meridian[and-cuda,scenarioplanner]) (4.2.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth->google-meridian[and-cuda,scenarioplanner]) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /usr/local/lib/python3.12/dist-packages (from google-auth->google-meridian[and-cuda,scenarioplanner]) (49.0.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth->google-meridian[and-cuda,scenarioplanner]) (4.9.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (0.47.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography>=38.0.3->google-auth->google-meridian[and-cuda,scenarioplanner]) (2.0.0)
Requirement already satisfied: attrs>=18.2.0 in /usr/local/lib/python3.12/dist-packages (from dm-tree->tfp-nightly==0.26.0.dev20260130->google-meridian[and-cuda,scenarioplanner]) (26.1.0)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client->google-meridian[and-cuda,scenarioplanner]) (1.28.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair>=5->google-meridian[and-cuda,scenarioplanner]) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair>=5->google-meridian[and-cuda,scenarioplanner]) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair>=5->google-meridian[and-cuda,scenarioplanner]) (2026.5.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (0.19.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth->google-meridian[and-cuda,scenarioplanner]) (0.6.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (2026.6.17)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (3.1.8)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair>=5->google-meridian[and-cuda,scenarioplanner]) (3.0.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth->google-meridian[and-cuda,scenarioplanner]) (3.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow<2.21,>=2.19.0->google-meridian[and-cuda,scenarioplanner]) (0.1.2)

In [ ]:
# Now, run this cell and we can test if all dependencies are appropratly installed
import tensorflow_probability as tfp
import pandas as pd

from meridian import constants
from meridian.data import data_frame_input_data_builder
from meridian.model import model
from meridian.model import prior_distribution
from meridian.model import spec

from meridian.schema.processors import model_fit_processor
from meridian.schema.processors import marketing_processor
from meridian.schema.processors import budget_optimization_processor
from meridian.schema.utils import date_range_bucketing
from meridian.schema.serde import meridian_serde

from scenarioplanner.converters import sheets
from scenarioplanner.converters.dataframe import dataframe_model_converter
from scenarioplanner import mmm_ui_proto_generator as mmm_ui_gen
from scenarioplanner.linkingapi import url_generator

In [ ]:
# --- FAST SETUP ---
spreadsheet_name = "Meridian Fast Report"
opt_name = "Fast Demo"
include_non_paid = True

# Speed Tip: Setting this to False avoids heavy Reach/Frequency curve calculations
use_opt_freq = False

# Speed Tip: Only use one generator (e.g., Quarterly) to save processing time
time_generators = [date_range_bucketing.QuarterlyDateRangeGenerator]

# 1. Define Constraints (Condensed)
constraints = [
    budget_optimization_processor.ChannelConstraintRel(c, 1.0, 1.0)
    for c in mmm.input_data.get_all_paid_channels()
]

# 2. Build Specs
budget_spec = budget_optimization_processor.BudgetOptimizationSpec(
    optimization_name=opt_name,
    grid_name="fast-grid",
    constraints=constraints,
    use_optimal_frequency=use_opt_freq,
)

summary_spec = marketing_processor.MediaSummarySpec(include_non_paid_channels=include_non_paid)

# 3. Generate Proto & Convert (Combined)
print("Processing model data (Fast Mode)...")
mmm_proto = mmm_ui_gen.create_mmm_ui_data_proto(
    mmm=mmm,
    specs=[
        model_fit_processor.ModelFitSpec(),
        marketing_processor.MarketingAnalysisSpec(media_summary_spec=summary_spec),
        budget_spec,
    ],
    time_breakdown_generators=time_generators,
)

dataframes = dataframe_model_converter.DataFrameModelConverter(mmm_proto)()

# 4. Upload & Link
spreadsheet = sheets.upload_to_gsheet(dataframes, credentials, spreadsheet_name=spreadsheet_name)
url = url_generator.create_report_url(spreadsheet)

print(f"Done! Spreadsheet: {spreadsheet.url}")
from IPython.display import HTML
HTML(f'<a href="{url}" style="font-size:20px;">Click here to open Looker Studio Report</a>')

Processing model data (Fast Mode)...

/usr/local/lib/python3.12/dist-packages/meridian/analysis/analyzer.py:2115: UserWarning: `split_by_holdout_id` is True but `holdout_id` is `None`. Data will not be split.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/analysis/analyzer.py:102: UserWarning: The `aggregate_geos` argument is ignored in the national model. It will be reset to `True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/analysis/analyzer.py:102: UserWarning: The `aggregate_geos` argument is ignored in the national model. It will be reset to `True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/analysis/analyzer.py:352: UserWarning: Setting `use_kpi=True` has no effect when `kpi_type=REVENUE` since in this case, KPI is equal to revenue.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/analysis/analyzer.py:352: UserWarning: Setting `use_kpi=True` has no effect when `kpi_type=REVENUE` since in this case, KPI is equal to revenue.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/analysis/analyzer.py:352: UserWarning: Setting `use_kpi=True` has no effect when `kpi_type=REVENUE` since in this case, KPI is equal to revenue.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/analysis/analyzer.py:352: UserWarning: Setting `use_kpi=True` has no effect when `kpi_type=REVENUE` since in this case, KPI is equal to revenue.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/analysis/analyzer.py:352: UserWarning: Setting `use_kpi=True` has no effect when `kpi_type=REVENUE` since in this case, KPI is equal to revenue.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/analysis/analyzer.py:352: UserWarning: Setting `use_kpi=True` has no effect when `kpi_type=REVENUE` since in this case, KPI is equal to revenue.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/analysis/analyzer.py:352: UserWarning: Setting `use_kpi=True` has no effect when `kpi_type=REVENUE` since in this case, KPI is equal to revenue.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/analysis/analyzer.py:352: UserWarning: Setting `use_kpi=True` has no effect when `kpi_type=REVENUE` since in this case, KPI is equal to revenue.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/meridian/analysis/analyzer.py:352: UserWarning: Setting `use_kpi=True` has no effect when `kpi_type=REVENUE` since in this case, KPI is equal to revenue.
  warnings.warn(
WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.
WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.

Done! Spreadsheet: https://docs.google.com/spreadsheets/d/11pklPriidMpUaTeOQQzvdl41ZEFTdSYdZ6Ce0U6BWQY/edit